default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>_test

production:
  primary:
    <<: *default
  cache:
    <<: *default
    database: <%= ENV["DATABASE_URL"] %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV["DATABASE_URL"] %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV["DATABASE_URL"] %>_cable
    migrations_paths: db/cable_migrate
